---
title: 'Mathematics and Statistics'
subtitle: 'Openday 2022'
output:
  xaringan::moon_reader:
    css: [default, default-fonts, "custom.css"]
    nature:
      highlightStyle: tomorrow
      highlightLines: true
      countIncrementalSlides: false
      ratio: "16:9"
      slideNumberFormat: |
        <div class="progress-bar-container">
          <div class="progress-bar" style="width: calc(%current% / %total% * 100%);">
          </div>
        </div>
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
library(palmerpenguins)
penguins = na.omit(penguins)
#data(package = 'palmerpenguins')
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.dim=c(4.8, 4.5), fig.retina=2, out.width="100%")
```

# Monty Hall: Changing minds with Statistics

There are 3 doors. Behind one of the doors is a prize.

A contestant is asked to choose a door.

The host then opens one of the other two doors, revealing that
the prize isn't behind it.

The contestant can then choose to stick with the door they originally picked, or switch to the other remaining door.

**What do you do?**

---

## Greedy pig

Greedy pig is a game where players take turns rolling a single die.

- On your turn, you may roll the die as many times as you want, until you either choose to stop or roll a one.

    - If you choose to stop, your score for this turn is the sum of the numbers you rolled.
    - If you roll a one, your score for this turn is zero.

- The winner is the first player to reach a total score of 100

**Should you roll again? What strategy might you choose to decide?**

---

## Seven questions, one lie

- Choose a number between $0$ and $15$ inclusive. The number must be an integer.

- I'll ask you seven yes-no questions.

- You answer the questions, and may lie up to once if you want to.

- I'll tell you your number, whether you lied, and if so on which question -- just using maths!

---

## Seven questions, one lie

Is your number...

1. one of $8,9,10,11,12,13,14,15$?

2. one of $4,5,6,7,12,13,14,15$?

3. one of $2, 3, 6, 7, 10, 11, 14, 15$?

4. odd?

5. one of $1, 2, 4, 7, 9, 10, 12, 15$?

6. one of $1, 2, 5, 6, 8, 11, 12, 15$?

7. one of $1, 3, 4, 6, 8, 10, 13, 15$?

**Tell me your answers, and I'll tell you your number!**

---

class: middle, inverse

# Solutions

---

## Monty Hall: Why you should change your mind

If you switch doors in the game you double your chances of winning! Why?

If you don't change your mind, there's a 1 in 3 chance of winning as there are 3 doors, and so the chance the prize is behind the one you picked is 1 in 3.

If you do change your mind, then the only way you lose is if the prize is behind the door you first picked (1 in 3). Thus, you must win 2 out of 3 times.

---

## Greedy Pig: Optimal score strategy

Suppose your score is currently $s$. If you roll again your score increases to:

next roll | probability | score
----------|-------------|-------
1         | 1/6         | 0
2         | 1/6         | s+2
3         | 1/6         | s+3
4         | 1/6         | s+4
5         | 1/6         | s+5
6         | 1/6         | s+6

Your expected score is $\frac{1}{6}(s+2 + s+3 + s+4 + s+5 + s+6) = \frac{1}{6}(5s+20)$.

You should roll if
$$\begin{align}\frac{1}{6}(5s+20) &> s\\ \Rightarrow 5s+20 &> 6s\\ \Rightarrow s &<20\end{align}$$


