---
title: 'Mathematics and Statistics'
subtitle: 'Openday 2022'
output:
  xaringan::moon_reader:
    seal: false
    css: xaringan-themer.css
    includes:
      in_header: repeat_slides.html
    nature:
      autoplay: 100
      ratio: "16:9"
      slideNumberFormat: ""
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(showtext)
library(ggplot2)
font_add_google("Work Sans", regular.wt=900, "raleway")
knitr::opts_chunk$set(echo=FALSE)
showtext_auto()
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_mono_accent(
  base_color = "#1c5253",
  background_color = "#31c9e8",
  inverse_text_color = "#000000",
  text_color = "#ffffff",
  header_color = "#ffffff",
  inverse_header_color = "#000000",
  inverse_background_color = "#31c9e8",
  header_h1_font_size = "5rem",
  header_font_google = google_font("Work Sans", "900"),
  text_font_google   = google_font("Work Sans", "900"),
  code_font_google   = google_font("Work Sans", "900"),
  colors = c(
    blue = "#31c9e8",
    pink = "#ea86f7",
    gold = "#fcc153"
  )
)
```

```{r, message=FALSE, warning=FALSE, results='asis'}
draw_slogan <- function(sentence1, sentence2, delay1=10, delay2=50, col="blue") {
  col = paste0('bg-', col)
  class = paste0("\n\n---\nclass: center, middle, ", col, "\n")
  for (i in 1:nchar(sentence1)) {
    cat(class)
    cat("# ", substring(sentence1, 1, i), "\n")
  }

  for (i in 1:10) {
    cat(class)
    cat("# ", sentence1, "\n")
  }

  for (i in 1:nchar(sentence2)) {
    cat(class)
    cat("# ", sentence1, "\n")
    cat(paste0("# .inverse.", col,"[", substring(sentence2, 1, i), "]"))
  }

  for (i in 1:50) {
    cat(class)
    cat("# ", sentence1, "\n")
    cat(paste0("# .inverse.", col,"[", sentence2, "]"))
  }
}

draw_slogan("ARE YOU LYING?", "WE CAN TELL.")
```

```{r, message=FALSE, warning=FALSE, results='asis'}
draw_slogan("ARE YOU GREEDY?", "WE CAN HELP.", col='pink')
```

```{r, message=FALSE, warning=FALSE, results='asis'}
draw_slogan("DO YOU FEEL LUCKY?", "CHANGE YOUR MIND.", col="gold")
```
